export enum BloodType {
  A_POS = "A_POS",
  A_NEG = "A_NEG",
  B_POS = "B_POS",
  B_NEG = "B_NEG",
  AB_POS = "AB_POS",
  AB_NEG = "AB_NEG",
  O_POS = "O_POS",
  O_NEG = "O_NEG",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum PatientType {
  EMERGENCY_SURGERY = "EMERGENCY_SURGERY",
  ONCOLOGIC = "ONCOLOGIC",
  TRAFFIC_ACCIDENT = "TRAFFIC_ACCIDENT",
  COMPLICATED_DELIVERY = "COMPLICATED_DELIVERY",
  CHILD_ANEMIA = "CHILD_ANEMIA",
  ELECTIVE_SURGERY = "ELECTIVE_SURGERY",
  ELDERLY_PATIENT = "ELDERLY_PATIENT",
  HEMATOLOGIC_DISEASE = "HEMATOLOGIC_DISEASE",
}

export enum UsageDescription {
  CARDIAC_SURGERY_TRANSFUSION = "CARDIAC_SURGERY_TRANSFUSION",
  LEUKEMIA_TREATMENT = "LEUKEMIA_TREATMENT",
  MULTIPLE_TRAUMA_REPLACEMENT = "MULTIPLE_TRAUMA_REPLACEMENT",
  POSTPARTUM_HEMORRHAGE = "POSTPARTUM_HEMORRHAGE",
  SEVERE_ANEMIA_TREATMENT = "SEVERE_ANEMIA_TREATMENT",
  LIVER_TRANSPLANT_SURGERY = "LIVER_TRANSPLANT_SURGERY",
  DIGESTIVE_ULCER_TREATMENT = "DIGESTIVE_ULCER_TREATMENT",
  APLASTIC_ANEMIA_TRANSFUSION = "APLASTIC_ANEMIA_TRANSFUSION",
}

export enum HospitalName {
  HOSPITAL_CENTRAL = "HOSPITAL_CENTRAL",
  HOSPITAL_SANTA_FE = "HOSPITAL_SANTA_FE",
  MATERNIDADE_SAO_JOSE = "MATERNIDADE_SAO_JOSE",
}

export type ID = string;

export const DEFAULT_POINTS_EARNED = 100;
